### ISSUE TITLE
建议增加通知功能

### ISSUE THREAD

**Issue by xxllllll** [dr34m-cn/taosync#14]
建议增加通知功能，如Bark,企业微信等，不知道大佬有无计划。

**Comment by dr34m-cn** [comment]
感谢你的建议，这是个好主意。预计将来某个版本会通过接入“方糖”之类的第三方来实现通知；也可能实现邮件通知等。方案可能随时改变，以后续实际为准

**Comment by i80980** [comment]
这个很有必要，可以优先开放么

**Comment by i80980** [comment]
> 感谢你的建议，这是个好主意。预计将来某个版本会通过接入“方糖”之类的第三方来实现通知；也可能实现邮件通知等。方案可能随时改变，以后续实际为准

这个很有必要，可以优先开发么

**Comment by dr34m-cn** [comment]
> > 感谢你的建议，这是个好主意。预计将来某个版本会通过接入“方糖”之类的第三方来实现通知；也可能实现邮件通知等。方案可能随时改变，以后续实际为准
> 
> 这个很有必要，可以优先开发么

你个人希望是什么形式的推送呢？邮件？[Server酱](https://sct.ftqq.com/)？还是其他（请补充）

**Comment by i80980** [comment]
> > > 感谢你的建议，这是个好主意。预计将来某个版本会通过接入“方糖”之类的第三方来实现通知；也可能实现邮件通知等。方案可能随时改变，以后续实际为准
> > 
> > 
> > 这个很有必要，可以优先开发么
> 
> 你个人希望是什么形式的推送呢？邮件？[Server酱](https://sct.ftqq.com/)？还是其他（请补充）

钉钉，Gotify，WxPusher这三个我在用

**Comment by Lumysia** [comment]
建议考虑兼容https://ntfy.sh/或者就拿它实现webhook类别的通知，它的客户端支持几乎所有平台包括web，并且它本身是FOSS软件，可以作为android上的UnifiedPush通知通道。

**Comment by ardenyang** [comment]
跟随许愿通知功能，希望增加在任务完成后，发送钉钉通知。多谢。

**Comment by dr34m-cn** [comment]
已在 [提交](https://github.com/dr34m-cn/taosync/commit/c4d32842240b096948e791f904ee20ae5efa2cd7) 中完成基本功能，并发布开发版，预计将在1-3周的测试后发布正式版
