### ISSUE TITLE
建议增加压缩功能

### ISSUE THREAD

**Issue by duaniu** [dr34m-cn/taosync#15]
增量备份功能很实用，如果能增加压缩功能就更好啦。
个人计划使用场景是配合alist的加密上传将一部分照片和视频放到oss等冷备份，如果有压缩功能可以缩减一部分消费。
如果能配合rar的恢复记录就更好了，国内云盘始终是有一些丢数据的可能。

**Comment by dr34m-cn** [comment]
目前基于alist的方式较难实现压缩。
以后等我们实现自己的不基于alist的引擎后，将重新研究解决方案。

**Comment by duaniu** [comment]
好的佬，感谢回复！

**Comment by PrestarLin** [comment]
> 目前基于alist的方式较难实现压缩。
> 以后等我们实现自己的不基于alist的引擎后，将重新研究解决方案。

目前有个开源项目叫做duplicati，可以参考

**Comment by dr34m-cn** [comment]
> > 目前基于alist的方式较难实现压缩。
> > 以后等我们实现自己的不基于alist的引擎后，将重新研究解决方案。
> 
> 目前有个开源项目叫做duplicati，可以参考

感谢提供建议
