### ISSUE TITLE
可以同步子文件夹的文件吗？多少层级？

### ISSUE THREAD

**Issue by bfbfcom** [dr34m-cn/taosync#17]
可以同步 子文件夹 的文件吗？多少层级？
我今天测试的vps上的报错了。

执行任务失败，原因为：('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by bfbfcom** [comment]
找到原因了，不能用域名 反向代理

**Comment by bfbfcom** [comment]
找到原因了，不能  用 域名反向代理

**Comment by bfbfcom** [comment]
好像不支持创建子文件夹， 也没法同步 子文件夹 下的文件

**Comment by dr34m-cn** [comment]
理论上可以无限层级同步

**Comment by bfbfcom** [comment]
> 理论上可以无限层级同步

需要提前 创建好，对应的子文件夹 吧? 不能自动创建

**Comment by dr34m-cn** [comment]
这个可能和网盘或alist有关，目前测试的阿里、百度、115、123都可以自动创建子文件夹，无需手动创建；还没有遇到必须要手动创建文件夹的情况。

**Comment by bfbfcom** [comment]
查了 两个没创建的文件夹， 原来是空的，没有文件。hen好用
