### ISSUE TITLE
错误原因 请升级到最新版本: unexpected error

### ISSUE THREAD

**Issue by Mohen-noname** [dr34m-cn/taosync#29]
最近几天一直显示同步失败  错误原因：请升级到最新版本: unexpected error
[Uploading 错误原因.bmp…]()

**Comment by dr34m-cn** [comment]
看不到图片，但估计是alist版本低了导致的，可以检查下alist的版本，还有alist挂载的网盘能否正常访问；alist当前最新版是3.38.0

**Comment by Mohen-noname** [comment]
已解决  非常感谢 就是alist没更新到最新版的问题
