### ISSUE TITLE
对taosync的一些反馈和建议

### ISSUE THREAD

**Issue by fzlychee2019** [dr34m-cn/taosync#33]
同步任务是从本地同步到天翼云盘，同步文件时，进度条开始是0%，有数据传输后，马上就跳到100%，没有中间过程。

文件名比较长的，显示不完整，只显示出一部分文件名来，这样看不出具体是哪个文件了。

详情是否能集中到同一个页面显示呢？目前得在任务主页上点详情后才能看到任务整体信息，然后再点详情才能看到当前同步的文件，步骤有些繁琐，把这些信息都直接集中到一个页面上，就会直观得多了。整体详情直接集中到任务列表页上，明细详情一个页面就全部展示出来，是不是会更好些。

详情不会自动刷新，得手动刷新，是不是能象宝塔的日志一样，搞个手动定义刷新时间，这样有个定时刷新，会方便许多，特别玩NAS的人多数都有强制症，没事时，喜欢盯着屏幕看进度，再去手动每次点刷新，挺麻烦的。

**Comment by dr34m-cn** [comment]
首先感谢您提出的反馈和建议

1. 进度跳100%确实是可能存在的，因为为了节约资源，传输进度其实并不是实时刷新的，而是有一个至少10秒的间隔（文件多的时候该间隔会更长以节约资源），如果在这个间隔内文件传完了，就会是直接跳；大文件则有可能看到非100%的情况；目前确实有思路可以既能实现几乎实时刷新，又不占用太多资源，但是实现起来复杂些，且需要更完善的逻辑来避免遗漏。因个人原因最近比较忙，该优化可能要很久才会提上日程。
2. 目前的详情是基于任务的，任务是基于作业的，这样的设计模式导致不容易做更直观地展示；
