### ISSUE TITLE
同步时间间隔的问题

### ISSUE THREAD

**Issue by Joker-lm** [dr34m-cn/taosync#35]
首先感谢作者大佬的付出！

问题 1，如果我设置同步时间间隔比较小的话应该不会对网盘造成频繁访问吧，这个比对的是 alist 的缓存目录吗？alist 的目录刷新好像默认是 10 分钟……

问题 2，作者大佬能优化一下手机浏览器访问时的 UI 吗，可以隐藏来源路径的显示和目标路径的显示，加个作业名称，这样就一目了然了。

再次感谢！软件很好用，帮了我大忙！

**Comment by dr34m-cn** [comment]
抱歉刚看到，前段时间换手机，邮件提醒忘记开了，错过了一些消息

问题1：同步速度选择“快速”，将使用alist缓存，否则如果使用较低的同步间隔会造成频繁访问网盘；

问题2：在考虑开发专门的适用于手机的UI，但是优先级低一些，还有一些更重要的工作要做。

**Comment by Joker-lm** [comment]
感谢大佬的回复，已知晓。
