### ISSUE TITLE
从夸克同步到nas的webdav失败

### ISSUE THREAD

**Issue by weiminghaoo** [dr34m-cn/taosync#38]
同步过程中，一直显示0，实际上会正常下载，但是当下载完成后，会从0重新开始
<img width="400" alt="image" src="https://github.com/user-attachments/assets/9e8cd7eb-c578-4da8-8d01-271d8a9afdd8">

最后会显示
<img width="291" alt="image" src="https://github.com/user-attachments/assets/c47399ae-b5e0-4d46-a5e2-f62dfff0d5e4">

这是我的配置
<img width="747" alt="image" src="https://github.com/user-attachments/assets/0c884117-6667-4b1c-bf4c-1fc4167da490">

**Comment by dr34m-cn** [comment]
这个错误应该已经在[#2847](https://github.com/AlistGo/alist/issues/2847) 修复了，你用的alist是哪个版本呢？

**Comment by weiminghaoo** [comment]
同步速度选高速的话 报这个错
<img width="310" alt="image" src="https://github.com/user-attachments/assets/9a442ae4-5cfd-4e3f-b2db-29cf97ea1413">

**Comment by weiminghaoo** [comment]
每次同步都要重复下载三四遍，同步完了重新开始 直到失败 
![](https://gitee.com/weiminghao/pic/raw/develop/202411161052880.gif)

**Comment by weiminghaoo** [comment]
找到原因了，我的本地存储是使用webdav挂载的
