### ISSUE TITLE
刚添加的alist（成功），执行任务报 alist链接失败

### ISSUE THREAD

**Issue by zhz-we** [dr34m-cn/taosync#40]
alist 是将本地磁盘的文件 放入 alist的 [Crypt](https://alist.nn.ci/zh/guide/drivers/crypt)加密文件夹的

![image](https://github.com/user-attachments/assets/a060e522-6fe9-43df-bd60-b5e81617dbeb)

![image](https://github.com/user-attachments/assets/f05cb384-de4f-49c8-9f18-a01b9510f878)

![image](https://github.com/user-attachments/assets/ef6b8919-ac32-435c-8ae4-288b1773dba1)

所有任务均是等待状态
![image](https://github.com/user-attachments/assets/65629060-7f18-40dc-81cd-47c702aed44f)

![image](https://github.com/user-attachments/assets/c12935ae-57f0-4df9-8c69-abe901bf6b83)

**Comment by dr34m-cn** [comment]
看起来是alist连接失败了，可以尝试重新配置引擎、重启alist等操作

**Comment by zhz-we** [comment]
> 看起来是alist连接失败了，可以尝试重新配置引擎、重启alist等操作

此前报了一次这个错误，然后删掉旧的alist，重新添加alist（有刷新令牌），然后创建【作业】执行

现在在删一次alist，再添加试试吧

**Comment by zhz-we** [comment]
> 看起来是alist连接失败了，可以尝试重新配置引擎、重启alist等操作

好像还是不行...一开始检查几个重复项（刚才有成功200多个文件），等一两分钟后就alist链接失败了
![image](https://github.com/user-attachments/assets/68501599-a259-4bc6-b1ab-f917985e4c91)
![image](https://github.com/user-attachments/assets/171e47ff-9fe2-4c0f-8d17-8a83c9e965af)
![image](https://github.com/user-attachments/assets/cb85e05e-a2a5-4542-b34e-e8e3c97dd259)

**Comment by dr34m-cn** [comment]
那有可能是alist挂掉了、连接满了、压力太大了之类的原因。

每次会有成功的项目吗，如果每次都有成功的，可以暂时忽略它，因为每次成功一点，慢慢就能全部成功了。

这个问题预计将在近1-2个月的一次更新中彻底修复。

**Comment by zhz-we** [comment]
> 那有可能是alist挂掉了、连接满了、压力太大了之类的原因。
> 
> 每次会有成功的项目吗，如果每次都有成功的，可以暂时忽略它，因为每次成功一点，慢慢就能全部成功了。
> 
> 这个问题预计将在近1-2个月的一次更新中彻底修复。

好像是哦。。。
我刚刚直接将这个文件夹给alist，alist网页死掉了...
![image](https://github.com/user-attachments/assets/70826501-8d44-4614-9055-476143c150f5)

![image](https://github.com/user-attachments/assets/054240a6-94ae-4065-8369-952a219c7f2f)
虚拟机也给了16G内存、16核心啊。。。不至于吧，请问大佬，这个是alist的问题吗？

**Comment by dr34m-cn** [comment]
目前来看，alist并没有很强的抗压能力，压力一大就容易崩溃、死掉，后续我考虑每次只给alist发一点点任务，做完了再发新的任务，有另外几个issue也提到这个问题了

**Comment by zhz-we** [comment]
> 目前来看，alist并没有很强的抗压能力，压力一大就容易崩溃、死掉，后续我考虑每次只给alist发一点点任务，做完了再发新的任务，有另外几个issue也提到这个问题了


辛苦大佬了🤝
