### ISSUE TITLE
同步的文件大小有问题

### ISSUE THREAD

**Issue by jeremyjone** [dr34m-cn/taosync#41]
感谢大佬付出😊

我比较好奇，为啥我从阿里云盘同步的电视剧，每一集都少15%左右。一开始我还以为是解码的问题，片源坏球了。后来才发现，同步到本地的视频大小和云盘上的不一样，每一个都差了大概15%左右，导致每一集播放到后半段就播不动了。

比如就拿甄嬛传说，我用咱这个直接创建手动同步，完事之后就这样：

云盘信息：
![Screenshot_2024-11-21-23-08-19-438_com.alicloud.databox-edit.jpg](https://github.com/user-attachments/assets/e64bab6b-b77e-422d-959d-726d3e17754a)

本地信息：
![Screenshot_2024-11-21-23-07-52-079_com.ugreen.pro-edit.jpg](https://github.com/user-attachments/assets/bfee60a4-d606-4ed5-ac5a-65aee92ab8c2)

我看了一下，也不需要配置啥啊？但是就是少。求解……

**Comment by jeremyjone** [comment]
我已经做过：关闭docker，重启，把所有同步的视频删除，再次创建新的同步任务，手动启动，down下来之后还是这样的。就好奇怪……

**Comment by dr34m-cn** [comment]
这个太奇怪了，试下从alist直接复制资源到本地呢？
