### ISSUE TITLE
The.Queen's.Corgi.2019 同步到夸克之后 会变成  The.Queen&#39;s.Corgi.2019

### ISSUE THREAD

**Issue by epenli** [dr34m-cn/taosync#43]
The.Queen's.Corgi.2019 同步到夸克之后 会变成  The.Queen&#39;s.Corgi.2019
' 会变成字符串 &#39;

**Comment by epenli** [comment]
&#39; 是 HTML 实体，它代表的是单引号字符 '。它通常用于网页中以避免与 HTML 代码中的标记冲突。

例如，在 HTML 中直接使用 ' 可能会与属性的引号冲突，而使用 &#39; 可以避免这个问题，确保字符能够正确显示。

如果你在命令行或者脚本中看到类似的表示，它们可能是通过 HTML 编码的方式显示出来的。你可以将它转化回普通的字符 '。

**Comment by epenli** [comment]
& # 39; 是 HTML 实体，它代表的是单引号字符 '。它通常用于网页中以避免与 HTML 代码中的标记冲突。

例如，在 HTML 中直接使用 ' 可能会与属性的引号冲突，而使用 &#39; 可以避免这个问题，确保字符能够正确显示。

如果你在命令行或者脚本中看到类似的表示，它们可能是通过 HTML 编码的方式显示出来的。你可以将它转化回普通的字符 '。

**Comment by dr34m-cn** [comment]
感谢反馈，该问题确实存在，经过验证，该问题是夸克的问题，即使从浏览器上传，或者通过重命名等方式，都会导致该问题。

该问题与taoSync或AList无关
