### ISSUE TITLE
[功能需求] 希望可以在作业管理中增加一个『手动执行一次所有作业』的功能

### ISSUE THREAD

**Issue by viklion** [dr34m-cn/taosync#45]
首先感谢作者，用了一段时间属实好用，thanks！
功能需求：有时候网盘转存了剧集的最新更新，但是又没到设定的自动执行同步的时间（或者设置的仅手动），作业一多挨个点手动执行有点麻烦，所以希望能增加一个手动执行一次所有作业的功能，或者自选批量手动执行一次作业

**Comment by dr34m-cn** [comment]
挨个点麻烦是不是因为需要先展开作业，再点『手动执行』，这样两部才觉得麻烦？（N个作业的点击次数是2N）

如果把手动执行提出来，不用展开直接点是不是就好多了。（这样N个作业的点击次数是N，比自选批量执行（N+1）少一次点击）

**Comment by dr34m-cn** [comment]
『手动执行所有』会随着版本更新加上

**Comment by dr34m-cn** [comment]
已添加该功能，预计未来数周内发布正式版

**Comment by viklion** [comment]
> 已添加该功能，预计未来数周内发布正式版

感谢感谢~
