### ISSUE TITLE
限制请求频率

### ISSUE THREAD

**Issue by muxinxy** [dr34m-cn/taosync#6]
不知道为什么我同步 OneDrive 的时候报错`The request has been throttled`，猜测可能是请求频率过高，所以想问一下能否限制请求频率

**Comment by dr34-m** [comment]
如果是查询请求频次过高，可以尝试修改同步速度为快速(将使用alist缓存)。另外也可以尝试到alist网站找下有没有遇到问题的朋友，看下他们的解决方式。

**Comment by dr34-m** [comment]
> > 如果是查询请求频次过高，可以尝试修改同步速度为快速(将使用alist缓存)。另外也可以尝试到alist网站找下有没有遇到问题的朋友，看下他们的解决方式。
> 
> 我用 Rclone 同时同步两个文件是没问题的，希望可以设置同时下载或上传的文件数量

目前限制的同时上传数量是5（由AList限制），之后我将尝试验证这个问题，并可能做出应对方法。修改同步速度为快速是否会有帮助呢？

**Comment by muxinxy** [comment]
> > > 如果是查询请求频次过高，可以尝试修改同步速度为快速(将使用alist缓存)。另外也可以尝试到alist网站找下有没有遇到问题的朋友，看下他们的解决方式。
> > 
> > 
> > 我用 Rclone 同时同步两个文件是没问题的，希望可以设置同时下载或上传的文件数量
> 
> 目前限制的同时上传数量是5（由AList限制），之后我将尝试验证这个问题，并可能做出应对方法。修改同步速度为快速是否会有帮助呢？

没有，应该主要是同时下载或上传的文件数量，也可能与重试时间间隔有关

**Comment by dr34-m** [comment]
> > > > 如果是查询请求频次过高，可以尝试修改同步速度为快速(将使用alist缓存)。另外也可以尝试到alist网站找下有没有遇到问题的朋友，看下他们的解决方式。
> > > 
> > > 
> > > 我用 Rclone 同时同步两个文件是没问题的，希望可以设置同时下载或上传的文件数量
> > 
> > 
> > 目前限制的同时上传数量是5（由AList限制），之后我将尝试验证这个问题，并可能做出应对方法。修改同步速度为快速是否会有帮助呢？
> 
> 没有，应该主要是同时下载或上传的文件数量，也可能与重试时间间隔有关

Alist官方看到了类似的问题，官方暂时没有回复[https://github.com/alist-org/alist/issues/6322](https://github.com/alist-org/alist/issues/6322)
